# This is a TOML-format config document that contains all the input parameters.
# Wherever [-] appears, if you want to type 75%, please type 0.75

title = "static form for measure"

# choice = 0 means no measure, choice = 1 means there is measure
choice = 0 

pr_meas_area = 100
cp_meas_area = 200
op_meas_area = 300
up_meas_area = 400
swds_meas_area = 500
mss_meas_area = 600
ow_meas_area = 700


