# This is a TOML-format config document that contains all the input parameters.
# Wherever [-] appears, if you want to type 75%, please type 0.75

title = "static form"

# time step [s]
timestep = 3600

# total area [m^2]
tot_area = 10000

# soil type and crop type
soiltype = 2
croptype = 1

# input type [type:0 = fraction (default), 1 = area]:
type = 0

# Paved Roof parameters:
# total area of paved roof [m^2]
# Paved roof fraction of total [-]
# part of buildings above Groundwater [-]
# part of paved roof area disconnected from sewer [-]
tot_pr_area = 1560
pr_frac = 0.156
frac_pr_aboveGW = 0
discfrac_pr = 0

# Closed Paved parameters:
# total area of closed paved [m^2]
# closed paved fraction of total [-]
# part of closed paved area disconnected from sewer [-]
tot_cp_area = 1171.28668
cp_frac = 0.1171286679
discfrac_cp = 0

# Open Paved parameters:
# total area of open paved [m^2]
# open paved fraction of total [-]
# part of open paved area disconnected from sewer [-]
tot_op_area = 113.713321
op_frac = 0.01137133209
discfrac_op = 0

# unpaved parameters:
# total area of unpaved [m^2]
# unpaved fraction of total [-]
tot_up_area = 6855
up_frac = 0.6855

# Open Water parameters:
# total area of open water [m^2]
# open water fraction of total [-]
# part of open water above Groundwater [-]
tot_ow_area = 300
ow_frac = 0.03
frac_ow_aboveGW = 0

# Unsaturated Zone parameters:
# Area of unsaturated zone is assumed to be equal to the area of unpaved area:
# uz_frac = up_frac, tot_uz_area = tot_up_area

# Groundwater parameters:
# Groundwater fraction/area is not directly read from config file. 
# Instead, it is calculated by the formula below:
# gw_frac = pr_frac * frac_pr_aboveGW + cp_frac + op_frac + up_frac + ow_frac * frac_ow_aboveGW
# tot_gw_area = gw_frac * tot_area
  
# Storm Water Drainage System (SWDS) parameters:
swds_frac = 1

# interception storage capacity parameters
# interception storage capacity on the surface of paved roof [mm]
# interception storage capacity on the surface of closed paved [mm]
# interception storage capacity on the surface of open paved [mm]
# interception storage capacity on the surface of unpaved [mm]
# open water storage capacity [mm]
# storage capacity of storm water drainage system [mm]
# storage capacity of mixed sewer system [mm]
intstorcap_pr = 1.6
intstorcap_cp = 1.6
intstorcap_op = 1.6
intstorcap_up = 20
storcap_ow = 1500
storcap_swds = 2
storcap_mss = 9

# infiltration capacity parameters
# infiltration capacity of the open paved area [mm/d]
# infiltration capacity of the unpaved area [mm/d]
infilcap_op = 0
infilcap_up = 48

# Groundwater parameters required in calculation
# groundwater drainage resistance w [d]
# defined seepage [type: 0=flux, 1=level]
# defined constant downward seepage flux [mm/d]
# initial groudwater level [m-SL]
# defined hydraulic head of deep groundwater [m-SL]
# flow resistance between deep and shallow groundwater vc [d]
w = 100
seep_def = 0
flux = 1
init_gwl = 1.5
h_deepgw = 21.5
vc = 20000


# required parameters in sewer system
# rainfall intensity when swds overflow on street [mm/timestep]
# rainfall intensity when mss overflow to open water [mm/timestep]
# pump capacity [lt/s/ha]
rainfall_swds_so = 58.7
rainfall_mss_ow = 27.9
pump_cap = 23.148

# required paramters in open water
# predefined discharge capacity from open water to outside water [mm/d]
# q_ow_out_cap is calculated from pump_cap q_ow_out_cap = pump_cap * 8.64


# initial values (I think only init_gwl_t0 is necessary here, other intial values can just be set as zeros)
init_intstor_pr_t0 = 0
init_intstor_cp_t0 = 0
init_intstor_op_t0 = 0
fin_stor_up_t0 = 0
# theta_uz_t0 is calculated from init_gwl_t0
init_gwl_t0 = 1.5
prev_stor_swds_t0 = 0
prev_so_swds_t0 = 0
prev_stor_mss_t0 = 0
prev_so_mss_t0 = 0

