[build-system]
requires = ["setuptools>=45", "setuptools-scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "urbanwb"
version = "0.2.0"
description = "Urban Water Balance"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Wenxing Zhang", email = "w.x.zhang93@gmail.com" }]
license = { text = "MIT" }
keywords = ["urban", "water", "balance", "modeling"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "numpy",
    "pandas",
    "toml",
    "openpyxl",
    "fire",
    "tqdm",
    "matplotlib",
    "tabulate",
    "setuptools",
]

[project.optional-dependencies]
dev = [
 "pytest",
 "ruff",
]

[project.urls]
Homepage = "https://github.com/Deltares-research/urbanwb"

[tool.ruff.lint]
select = [
    "B",
    "B",
    "C4",
    "D",
    "E",
    "F",
    "I",
    "LOG",
    "NPY",
    "PD",
    "RUF",
    "S",
    "SIM",
    "UP",
]
ignore = [
    "B006",
    "B904",
    "B905",
    "D1",
    "D200",
    "D203",
    "D205",
    "D213",
    "D400",
    "D401",
    "D415",
    "D417",
    "E501",
    "S101",
    "SIM118",
    "UP031",
]

[tool.setuptools]
packages = ["urbanwb"]
include-package-data = true

[tool.setuptools.package-data]
"*" = ["data/*.csv"]
